# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GYJTV' do

use_frameworks!

# Swift库
pod 'Alamofire'
pod 'Kingfisher'
pod 'ProtocolBuffers-Swift'
pod 'RxSwift'
pod 'RxCocoa'

# OC库
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'LFLiveKit'

end
